In [2]:
import numpy as np

In [3]:
from sklearn.preprocessing import StandardScaler

In [4]:
from sklearn.pipeline import make_pipeline

In [5]:
from sklearn.svm import SVC

In [6]:
X = np.array([
    [-1,-1],
    [-2,-1],
    [1,1],
    [2,1]
])

In [7]:
Y = np.array([1,1,2,2])

In [8]:
clf = make_pipeline(StandardScaler(), SVC(gamma = 'auto'))

In [9]:
clf.fit(X,Y)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('svc', SVC(gamma='auto'))])

In [11]:
clf.predict([[-1,-1]])

array([1])

In [17]:
from sklearn.datasets import load_iris

In [19]:
X,Y = load_iris(return_X_y = True)

In [20]:
clf1 = make_pipeline(StandardScaler(), SVC(gamma = 'auto'))

In [22]:
clf1.fit(X,Y)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('svc', SVC(gamma='auto'))])

In [23]:
clf1.predict(X[50:53])

array([1, 1, 1])

In [24]:
clf1.predict(X[:2])

array([0, 0])

In [25]:
clf1.predict(X[130:133])

array([2, 2, 2])